from dotenv import load_dotenv
import os

load_dotenv()

CLIENT_ID = os.getenv("CLIENT_ID", default="")
DIRECTORIO_PRINCIPAL = os.getenv("DIRECTORIO_PRINCIPAL", default="AndreaProyecto")
DIRECTORIO_REGISTRO_DIARIO = os.getenv("DIRECTORIO_REGISTRO_DIARIO", default="REGISTRO DIARIO")
DIRECTORIO_REGISTRO_SEMANAL = os.getenv("DIRECTORIO_REGISTRO_SEMANAL", default="REGISTRO SEMANAL")
DIRECTORIO_REGISTRO_NORMAL = os.getenv("DIRECTORIO_REGISTRO_NORMAL", default="NORMALES CLIMÁTICAS")
DIRECTORIO_PLANILLA = os.getenv("DIRECTORIO_PLANILLA", default="PLANILLA CLIMATOLOGICA")
ARCHIVO_EXCEL_NORMALES = os.getenv("ARCHIVO_EXCEL_NORMALES", default="NORMALES 1991-2020_ME.xlsx")
